#! /usr/bin/env python3
from dataclasses import *
from typing import List, Tuple, Dict, Set
import sys
import os

script_path = __file__
script_dir, script_name = os.path.split(script_path)
assert script_dir.endswith("examples")


@dataclass(slots=True)
class DirConfig:
    schedule_it: bool
    AB_type: str

    def make_dir_name(self):
        verb = "schedule" if self.schedule_it else "handwrite"
        return f"Sm90a_{self.AB_type}_{verb}_row_col_gemm"


type_letters = {
    "f32": "f",
    "f16": "h",
    "bf16": "b",
}


@dataclass(slots=True)
class FileConfig:
    ncta_M: int
    ncta_N: int
    enable_split_k: bool
    ping_pong: bool

    def make_file_name(self, dconf: DirConfig):
        strat = "pingpong" if self.ping_pong else "coop"
        k = "splitK" if self.enable_split_k else "os"
        prov = "S" if dconf.schedule_it else "H"
        types = "".join(type_letters[t] for t in (dconf.AB_type, dconf.AB_type, "f32", "f32"))
        return f"exocc_Sm90a_m{self.ncta_M}n{self.ncta_N}_{strat}_{k}_{prov}{types}.py"


@dataclass(slots=True)
class KernelConf:
    cta_M: int
    cta_N: int
    ring_depth: int

    def make_smem_usage(self, ping_pong: bool):
        M, N, R = self.cta_M, self.cta_N, self.ring_depth
        if ping_pong:
            return 4 * (M // 2) * N + 128 * R * (M + 2 * N)
        else:
            return max(4 * M * N, 128 * R * (M + N))


def make_file_contents(dconf: DirConfig, fconf: FileConfig, kconf_list: List[KernelConf]):
    make_gemm = "schedule_gemm" if dconf.schedule_it else "handwrite_gemm"
    warning = f"# ====== Autogenerated by {script_name}; don't hand edit ======"
    lines = []
    lines.append(warning)
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append(f"from exo.platforms.Sm90.tk_gemm_util import {make_gemm}, GemmConfig, f32, bf16")
    lines.append("from dataclasses import replace")
    lines.append(f"""
{warning}
base_config = GemmConfig(
    A_type={dconf.AB_type},
    B_type={dconf.AB_type},
    C_type=f32,
    D_type=f32,
    A_major="row",
    B_major="col",
    C_major="row",
    ncta_M={fconf.ncta_M},
    ncta_N={fconf.ncta_N},
    enable_split_k={fconf.enable_split_k},
    ping_pong={fconf.ping_pong},
)""")

    lines.append("")
    lines.append(warning)
    lines.append("cases = []")
    lines.append("")

    for kconf in kconf_list:
        smem_usage = kconf.make_smem_usage(fconf.ping_pong)
        assert smem_usage <= 227 << 10, (smem_usage, k, fconf)
        M, N, R = kconf.cta_M, kconf.cta_N, kconf.ring_depth
        exo_conf = f"replace(base_config, cta_M={M}, cta_N={N}, ring_depth={R})"
        lines.append(f"gemm_m{M}n{N}r{R} = {make_gemm}({exo_conf}, cases)")

    lines.append("")
    lines.append("import json")
    lines.append('json.dump(cases, open(__file__ + ".json", "w"))')
    return "\n".join(lines)


dir_configs = [
    DirConfig(schedule_it=False, AB_type="f32"),
    DirConfig(schedule_it=False, AB_type="bf16"),
    DirConfig(schedule_it=True, AB_type="f32"),
    DirConfig(schedule_it=True, AB_type="bf16"),
]

for dconf in dir_configs:
    dir_path = os.path.join(script_dir, dconf.make_dir_name())
    os.makedirs(dir_path, exist_ok=True)

    file_configs = []
    for (k, p) in ((False, False), (True, False), (False, True)):
        for (M, N) in ((1, 1), (2, 1), (1, 2)):
            fconf = FileConfig(ncta_M=M, ncta_N=N, enable_split_k=k, ping_pong=p)
            if not fconf.ping_pong or not dconf.schedule_it:
                # schedule_gemm doesn't support ping-pong kernel.
                file_configs.append(fconf)

    for fconf in file_configs:
        if fconf.ping_pong:
            kconf_list = [
                KernelConf(cta_M=256, cta_N=128, ring_depth=2),
                KernelConf(cta_M=128, cta_N=128, ring_depth=3),
                KernelConf(cta_M=128, cta_N=96, ring_depth=4),
            ]
        else:
            kconf_list = [
                KernelConf(cta_M=256, cta_N=192, ring_depth=4),
                KernelConf(cta_M=128, cta_N=256, ring_depth=4),
            ]
        code = make_file_contents(dconf, fconf, kconf_list)
        with open(os.path.join(dir_path, fconf.make_file_name(dconf)), "wb") as f:
            f.write(code.encode("utf-8"))
